// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1KmxVQtBeJBbYP5qSPNUv7SjUffmVFQY',
    appId: '1:298605773484:web:6053d24329c36f388d5509',
    messagingSenderId: '298605773484',
    projectId: 'spotifyclone-33084',
    authDomain: 'spotifyclone-33084.firebaseapp.com',
    storageBucket: 'spotifyclone-33084.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxfwCkkGk1kOlmXFijTG4AdhYlS2zYr5Q',
    appId: '1:298605773484:android:0e38989c151bfe068d5509',
    messagingSenderId: '298605773484',
    projectId: 'spotifyclone-33084',
    storageBucket: 'spotifyclone-33084.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARqQ6i4t6_fq8fQXSGQlSqrxHOIEfABgg',
    appId: '1:298605773484:ios:7272122428db5a518d5509',
    messagingSenderId: '298605773484',
    projectId: 'spotifyclone-33084',
    storageBucket: 'spotifyclone-33084.firebasestorage.app',
    iosClientId: '298605773484-g9fjen1apkm1a6qd2v0917kj41c3q1a6.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARqQ6i4t6_fq8fQXSGQlSqrxHOIEfABgg',
    appId: '1:298605773484:ios:7272122428db5a518d5509',
    messagingSenderId: '298605773484',
    projectId: 'spotifyclone-33084',
    storageBucket: 'spotifyclone-33084.firebasestorage.app',
    iosClientId: '298605773484-g9fjen1apkm1a6qd2v0917kj41c3q1a6.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1KmxVQtBeJBbYP5qSPNUv7SjUffmVFQY',
    appId: '1:298605773484:web:f68a9e869ccb638e8d5509',
    messagingSenderId: '298605773484',
    projectId: 'spotifyclone-33084',
    authDomain: 'spotifyclone-33084.firebaseapp.com',
    storageBucket: 'spotifyclone-33084.firebasestorage.app',
  );
}
